print ('\033[1m' + '\nCheatesheet v1.0\n' + '\033[0m')

print ("arp -a                   |  Scan local network")
print ("Ifconfig                 |  Wireless info")
print ("Sudo shutdown ___ now    |  Instant shutdown")
print ("uptime                   |  Check session time")
print ("caffeinate               |  Stay awake")
print ("alias                    |  Command pseudo")
print ("bind                     |  Display readline key and function bindings")
print ("halt                     |  Stop and reboot")
print (" ")